### ISSUE TITLE
Is default branch being next intentional?

### ISSUE THREAD

**Issue by dmitshur** [bugsnag/bugsnag-go#111]
Hi,

The default branch of this repository has recently become `next`. Up until now, it has always been `master`. Was this change intentional? It affects the `go get` command in GOPATH mode, since it fetches commits from the default remote branch.

Thanks!

**Comment by bengourley** [comment]
Hi @dmitshur, yes this change was intentional but the effect it had on `go get` was unanticipated and undesirable, so I have switched it back to `master`. Apologies if this caused you inconvenience or confusion, and thanks for rasing it 🙏.

The intention was to have an integration branch where we could land approved PRs without causing a release. Then when we choose to release, we make a single merge from `next` -> `master`. Using the default branch setting meant PRs would automatically use `next` as the base branch, but I guess this will just have to be manually set each time due to `go get`'s / GitHub's behaviour in this instance.

Thanks again!

**Comment by dmitshur** [comment]
> Apologies if this caused you inconvenience or confusion, and thanks for rasing it 🙏.

No problem. This did not cause me inconvenience, I just wanted to report it in case it was an unintentional change.

Thank you!
