### ISSUE TITLE
Unable to get Bugsnag to handle/report errors on AWS Lambda invocation failure

### ISSUE THREAD

**Issue by bensie** [bugsnag/bugsnag-go#127]
### Expected behavior
A Lambda function invocation that errors should notify Bugsnag.

### Observed behavior
Bugsnag is not notified (even when using the Synchronous: true option).

### Steps to reproduce
I've created a sample application [here](https://github.com/bensie/bugsnaglambda). It uses AWS SAM to make it easier to reproduce locally as well as deploy to Lambda.

* [Install SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html)
* Clone [the sample app](https://github.com/bensie/bugsnaglambda)
* Set a valid Bugsnag API key on line 13 of `main.go`
* `make build`
* `sam local invoke HelloWorldFunction`

I get the following output, which is identical to the log output that I'm seeing when deploying to production AWS Lambda. The JSON output at the bottom is expected and is what Lambda spits out to the log when an error occurs. The Bugsnag-specific part is the `listen tcp 127.0.0.1:54321: bind: address already in use` part (and the fact that it doesn't notify). Note that it sometimes doesn't log that "address already in use" line but it always fails to notify.

```
Invoking hello-world (go1.x)

Fetching lambci/lambda:go1.x Docker container image......
Mounting /Users/james/Code/bugsnaglambda/bugsnaglambda/hello-world as /var/task:ro,delegated inside runtime container
START RequestId: b1b178d4-955b-19fd-1832-d1d2679fa1b8 Version: $LATEST
END RequestId: b1b178d4-955b-19fd-1832-d1d2679fa1b8
REPORT RequestId: b1b178d4-955b-19fd-1832-d1d2679fa1b8	Init Duration: 148.02 ms	Duration: 5.44 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 22 MB	
2019/12/31 02:39:09 listen tcp 127.0.0.1:54321: bind: address already in use

{"errorType":"boundsError","errorMessage":"runtime error: index out of range [2] with length 2","stackTrace":["github.com/aws/aws-lambda-go/lambda/function.go:27 (*Function).Invoke.func1","runtime/panic.go:679 gopanic","runtime/panic.go:75 goPanicIndex","hello-world/main.go:21 handler","reflect/value.go:460 Value.call","reflect/value.go:321 Value.Call","github.com/aws/aws-lambda-go/lambda/handler.go:121 NewHandler.func1","github.com/aws/aws-lambda-go/lambda/handler.go:24 lambdaHandler.Invoke","github.com/aws/aws-lambda-go/lambda/function.go:59 (*Function).Invoke","reflect/value.go:460 Value.call","reflect/value.go:321 Value.Call","net/rpc/server.go:377 (*service).call","runtime/asm_amd64.s:1357 goexit"]}
```

### Version
v1.5.3

### Additional information
Manual, synchronous `bugsnag.Notify()` calls work as expected. The issue is with auto-handling errors like in the supplied code. Happy to provide any additional information if it would be helpful.

**Comment by mattdyoung** [comment]
Hi @bensie 

Thanks for the detailed info. We don't yet test our Go library against AWS Lambda or officially support this but I've discussed it with our product team. We plan to look at testing and documenting use of the library on AWS Lambda and any required implementation to get this working in the future when priorities allow.

Thanks!

**Comment by bensie** [comment]
Thanks @mattdyoung.

FWIW I was able to work around it for now by using the `defer` approach that is designed for use in goroutines, though I still get the tcp errors in the logs. Better than nothing! Thanks for considering official Lambda support!

```go
func handler(ctx context.Context) error {
	bugsnag.Configure(bugsnag.Configuration{
		APIKey: "x",
		ProjectPackages: []string{
			"main",
		},
		Synchronous: true,
	})
        defer bugsnag.AutoNotify(ctx)

	x := []string{"foo", "bar"}
	fmt.Println(x[2])

	return nil
}
```

**Comment by kerbyhughes** [comment]
Found this issue while also trying to use Bugsnag from a Lambda function and was seeing the `listen tcp ... bind: address already in use` error.

The [default PanicHandler configuration][0] uses [panicwrap][1], which `re-executes a Go binary and monitors stderr output from the binary for a panic`, similar to a fork. This second instance of the lambda process has the same environment variables, so when `aws-lambda-go` tries to [register an rpc listener][2] on the same port, it returns with the `address already in use` error.

The suggestion in the documentation to remove the `PanicHandler` func worked for our use case because we did not need that functionality.
```
bugsnag.Configure(bugsnag.Configuration{
    PanicHandler: func() {},
})
```

[0]: https://docs.bugsnag.com/platforms/go/net-http/configuration-options/#panichandler
[1]: https://pkg.go.dev/github.com/bugsnag/panicwrap?utm_source=godoc
[2]: https://github.com/aws/aws-lambda-go/blob/406b8fc429988d9ee04afc770794e79ed44a1964/lambda/rpc.go#L23

**Comment by bensie** [comment]
@kerbyhughes That's great to know! Other than that, are you using the same config as I posted above (synchronous + defer auto notify)?

**Comment by kerbyhughes** [comment]
> @kerbyhughes That's great to know! Other than that, are you using the same config as I posted above (synchronous + defer auto notify)?

I'm using `Synchronous: true`, but not `AutoNotify`. I'm just calling `bugsnag.Notify()` to send errors at expected places for our use case. From my understanding, I would expect `AutoNotify` to continue to work as expected without the `PanicHander` because `AutoNotify` catches the panic in a `recover()` call before calling `panic()` again, so it would log before any un-handled panic occurs, which is where `PanicHandler` would come in.

**Comment by bensie** [comment]
@kerbyhughes Finally got around to trying your suggestion and I can confirm it works as well! Removing the `PanicHandler` fixes the Lambda rpc error 👍 

Thanks!
