### ISSUE TITLE
How to identify errors with id's (UUIDs for example)

### ISSUE THREAD

**Issue by ORESoftware** [bugsnag/bugsnag-go#136]
Right now my account looks like this:

![Screenshot from 2020-09-20 19-49-46](https://user-images.githubusercontent.com/11139560/93729710-8ab63400-fb7a-11ea-89a1-05b07a17f9a3.png)

basically there are 10 events total, 1 event of type A and 9 events of type B.
My question is - how does bugsnag group them? Based off what information? The file + line number? It would be better for us to group them by id, we can manually provide a UUID, for example.

Sentry allows us to provide the event-id like so:

```golang 
sentryClient.CaptureEvent(&sentry.Event{
		Breadcrumbs: []*sentry.Breadcrumb{},
		EventID:     "0edd5580-f5c2-4743-a474-769ffd08b764",    // here
		Level:       sentry.LevelDebug,
		Message:     "this is my message 2",
		Tags:        map[string]string{"foo": "bar"},
		Spans: []*sentry.Span{},
	})
```

does bugsnag allow us to use our own event id like this? Want to be able to group errors by something we can control easily.

**Comment by ORESoftware** [comment]
for example, here there are 4 types of errors, the first 2 are really the same type, they just happen to on different lines of code since the version of the code changed:

![Screenshot from 2020-09-20 20-23-18](https://user-images.githubusercontent.com/11139560/93730834-36fa1980-fb7f-11ea-8ca6-224fca5c26f9.png)

**Comment by johnkiely1** [comment]
Hi @ORESoftware,

By default Bugsnag will group errors based on top in project stackframe but there are [various ways](https://docs.bugsnag.com/product/error-grouping/) you can group your errors both via the dashboard and via code. For maximum control over grouping behaviour I would suggest looking at a [custom grouping hash]( https://docs.bugsnag.com/platforms/go/other/customizing-error-reports/#overriding-bugsnag-39-s-grouping-algorithm). You can then use information from the report itself, such as UUID or any other field, to conditionally set a grouping hash string. All events with the same grouping hash will group together in the dashboard. It is worth noting that changing grouping behaviour will only apply to new events received and does not regroup existing dashboard errors.  If you need any assistance with your specific use case feel free to write in to us at support@bugsnag.com with links to the errors themselves and we will be happy to help.

**Comment by ORESoftware** [comment]
that would work, but:

```golang
bugsnag.OnBeforeNotify(
    func (event *bugsnag.Event, config *bugsnag.Configuration) error {
        event.GroupingHash = calculateGroupingHash(event)
        return nil
    })
```

I would need to be able to put a custom field in the bugsnag.Event object so I access that custom field (in this case UUID field) and use that for the grouping hash.

**Comment by johnkiely1** [comment]
HI @ORESoftware,

You can add additional information to a handled error by using [metadata](https://docs.bugsnag.com/platforms/go/other/reporting-handled-errors/#bugsnag-metadata) at the point `Notify` is called and access it again in the OnBeforeNotify. The value specified for the grouping hash does not need to be included in the event itself, you just need to be able to access it from within OnBeforeNofity, eg this could come from some kind of global variable.

If using the grouping hash, this doesn't need to apply to all errors. For your examples above you could use it to separate out the "errorString" errors that reference github. You could do this by checking if the [errorClass](https://docs.bugsnag.com/platforms/go/other/customizing-error-reports/#context) is `errors.errorString` and the [context](https://docs.bugsnag.com/platforms/go/other/customizing-error-reports/#errorclass) contains the string "github". If both of those conditions are true then add the grouping hash, effectively putting only those types of errors into their own group. The rest would group as normal. 

You could also look at [grouping by context](https://docs.bugsnag.com/product/error-grouping/#context), this would also make these errors group separately as they all have the same errorClass but different contexts. However this would be more granular that you were describing which is why I suggested using grouping hash which gives you more control.
