### ISSUE TITLE
Godef support

### ISSUE THREAD

**Issue by tobstarr** [bugsnag/bugsnag-go#14]
There seems to be an issue in combination with godef (http://godoc.org/code.google.com/p/rog-go/exp/cmd/godef), probably due to some build flags?

  ~/src/github.com/bugsnag/bugsnag-go $ godef -t -debug -f ./doc.go bugsnag.Configure
  2015/02/09 11:18:18 exprType tuple:false pkg: *ast.SelectorExpr bugsnag.Configure [
  2015/02/09 11:18:18 exprType tuple:false pkg: *ast.Ident bugsnag [
  2015/02/09 11:18:18 ] -> 0x0, Type{bad "" <nil> }
  2015/02/09 11:18:18 ] -> 0x0, Type{bad "" <nil> }
  godef: no declaration found for bugsnag.Configure

Any ideas?

**Comment by rogpeppe** [comment]
Your command line is wrong. It should be 

   godef -t -debug -f ./doc.go Configure

because "bugsnag" isn't a defined identifier in the bugsnag
package itself.

However, even with that, it still doesn't work, which is
due to a bug in godef. The issue is that when you pass
an expression on the command line, it's interpreted
in the context of the file that you've specified, but at that
point we have only read that one file and not the whole
package, so the identifier was not resolved then - we
need to reparse the expression.

This works fine, for example:

   godef -t -debug -f ./doc.go Configure

Please raise an issue at http://github.com/rogpeppe/godef
