### ISSUE TITLE
Anything above bugsnag.Configure is executed twice

### ISSUE THREAD

**Issue by ShariJoosten** [bugsnag/bugsnag-go#188]
### Describe the bug
If Bugsnag is configured, then once sts.GetCallerIdentity is called, the main function is invoked for a second time, which is strange and unexpected behaviour. This second invocation never completes, but appears from my testing to only execute the first couple of lines of code or something similar?

### Steps to reproduce
Check out my repo at https://github.com/ShariJoosten/BugsnagBug, install it with your usual go get and stuff, and then run it with your usual go run main.go

### Environment
Please see the go.mod file for all version info

**Comment by ShariJoosten** [comment]
Turns out that
```
package main

import (
	"fmt"

	"github.com/bugsnag/bugsnag-go/v2"
)

func main() {
	fmt.Println("Start of main!")
	bugsnag.Configure(bugsnag.Configuration{})
	fmt.Println("End of main!")
}
```

Also causes the same bug. So it has nothing to do with AWS.getCallerIdentity. It seems that anything above bugsnag.Configure is executed twice?

**Comment by benjamin-thomas** [comment]
Please document this better, and make it obvious right at the start here: https://docs.bugsnag.com/platforms/go/net-http/#basic-configuration

Quite a gotcha, which made me waste more time than I would like unfortunately.

It must be noted that one should **not** use the built in `init()` function in one's program **and** init bugsnag in `main`. Otherwise `main` and/or `init` get executed twice for the same reason.

Alternatively, initializing bugsnag at the top of `init()` seems to be ok

```golang
package main

func init() {
	initBugsnag() // must be called first!
	initOtherStuff()
}

func main() {
	println("My app is monitored now")
}
```
