### ISSUE TITLE
Unexpected behaviour with Singletons when using `Configure`

### ISSUE THREAD

**Issue by juliusbachnick** [bugsnag/bugsnag-go#32]
Hey all,

I'm facing an unexpected issue:

My `main.go` looks like:

```
package main

import(
        "foo"
	bugsnag "github.com/bugsnag/bugsnag-go"
)

func init(){
    instance := foo.Get()
    bugsnag.Configure(bugsnag.Configuration{
		APIKey:              "bar",
    })
}

func main(){
    //Code that is not executed twice
}
```

With `foo.go`:
```
package foo

import (
	"fmt"
	"sync"
)

type Context struct{}

var once sync.Once
var instance *Context

func Get() *Context {
	fmt.Printf("\nonce: %s\n", once)
	once.Do(func() {
		instance = &Context{}
		fmt.Printf("\ninstance: %s\n\n", instance)
	})

	return instance
}
```

When running this code, I get the following Code:
```

once: {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0)}
instance: &{}

once: {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0)}
instance: &{}
```

So it appears that `foo.Get()` is called twice. However, when I do not call `Configure` but instead do

```
bugsnag.Config.APIKey = "foo"
```

The `instance` appears only to be created once.

Regards,

Julius

**Comment by kattrali** [comment]
Hi @juliusbachnick, I apologize for the delayed response. This behavior is a side effect of initializing Bugsnag after other parts of the application, since monitoring unhandled panics requires wrapping the process and reporting the contents of stderr. I updated the documentation to make this clearer, and explain why Bugsnag should be initialized before the rest of the application:

* [Initial configuration](http://docs.bugsnag.com/platforms/go/other/#basic-configuration)
* [Reporting unhandled exceptions](http://docs.bugsnag.com/platforms/go/other/#reporting-unhandled-exceptions)

Hopefully this helps, feel free to reopen if you have any questions.
