### ISSUE TITLE
double call main func

### ISSUE THREAD

**Issue by dkostenko** [bugsnag/bugsnag-go#41]
Hello! Thank you for the package!

But there is one trouble with such code:

```
package main

import (
	"log"

	bugsnag "github.com/bugsnag/bugsnag-go"
)

func main() {
	log.Println("HELLO")
	bugsnag.Configure(bugsnag.Configuration{
		APIKey:       "",
		ReleaseStage: "production",
		AppVersion:   "",
	})
}
```

You will see double message HELLO in the terminal - this is a bug, am I right?

**Comment by bullmo** [comment]
Hi @dkostenko, Bugsnag needs to be initialized at the start of the application in order for it to work correctly. The behaviour that you are seeing is a side effect of Bugsnag being initialized after other calls (due to the way it wraps and monitors the application process to monitor unhandled errors).

More information can be found in the Go integration guide at https://docs.bugsnag.com/platforms/go/other/#basic-configuration.
