### ISSUE TITLE
[appengine]bad import "syscall" in github.com/bugsnag/bugsnag-go/sessions/tracker.go

### ISSUE THREAD

**Issue by amandeepm003** [bugsnag/bugsnag-go#99]
Upon go get of latest github.com/bugsnag/bugsnag-go and deploying on AppEngine after following suitable instruction from [example](https://github.com/bugsnag/bugsnag-go/blob/master/examples/appengine/hello.go) and [documentation](https://docs.bugsnag.com/platforms/go/app-engine/)

Still getting this error upon deployment attempt

**bad import "syscall" in github.com/bugsnag/bugsnag-go/sessions/tracker.go**

Is there a non-syscall version of bugsnag-go available to use over AppEngine?

**Comment by bengourley** [comment]
Hi @amandeepm003. Unfortunately app engine has changed a great deal since our library supported it and it would now take a significant amount of effort to add support. That's not something we can prioritise at this point in time.

We're removing app engine related code from the notifier (including the example) and content from our docs to avoid further confusion.

**Comment by amandeepm003** [comment]
I just made a local repo of our patched code that works for now in our
setup of GO and AppEngine backend deployment

Here it is: https://github.com/amaendeepm/bugsnag-go-appengine-patched
